install.packages("randomForest")
library(randomForest)
fraud<-read.csv("F://vag/Fraud_check.csv")
fraud_train<-rbind(fraud[1:500,])
fraud_train$Taxable.Income<-as.factor(fraud_train$Taxable.Income)
fraud_test<-rbind(fraud[501:600,])
fraud_test$Taxable.Income<-as.factor(fraud_test$Taxable.Income)
#training on the random forest
fit.forest<-randomForest(Taxable.Income~.,data = fraud_train,na.action = na.roughfix,importance=TRUE)
pred_train<-predict(fit.forest,fraud_train)
mean(fraud_train$Taxable.Income==pred_train)
Risky_Good<-ifelse(fraud$Taxable.Income<=30000,"Risky","Good")
fraud_train1<-data.frame(fraud,Risky_Good)
fraud_train2<-rbind(fraud_train1[1:500,])
fraud_test2<-rbind(fraud_train1[501:600,])
windows()
plot(fit.forest,lwd=2)
legend("topright",colnames(fit.forest$err.rate),col = 1.4,cex = 0.8,fill = 1:4)
install.packages("caret")
library(caret)
confusionMatrix(fraud_train$Taxable.Income,pred_train)
##predicting for the test data 
fit.forest1<-randomForest(Taxable.Income~.,data = fraud_test,na.action=na.roughfix,importance=TRUE)
pred_test<-predict(fit.forest1,fraud_test)
mean(fraud_test$Taxable.Income==pred_test)
plot(fit.forest1)
legend("topright",colnames(fit.forest1$err.rate),col = 1.4,cex = 0.8,fill = 1.4)
##using boosting method.
fit.forest4<-gbm(Taxable.Income~.,data =fraud_train2,distribution = "gaussian",n.trees = 2000,interaction.depth = 4 )
boost_pred<-predict(fit.forest4,fraud_train2,n.trees = 2000)
mean((boost_pred -fraud_train2$Taxable.Income)^2)
summary(fit.forest4)
##using test method
fit.forest5<-gbm(Taxable.Income~.,data = fraud_test2,n.trees = 2000,distribution = "gaussian",interaction.depth = 4)
boost_pred1<-predict(fit.forest5,fraud_test2,n.trees = 2000)
mean((boost_pred1 -fraud_test2$Taxable.Income)^2)
